nodeLinker: node-modules
defaultSemverRangePrefix: ''
cacheFolder: './node_modules/.__yarn__/cache'
deferredVersionFolder: './.yarn/versions'
enableImmutableInstalls: true
installStatePath: './node_modules/.__yarn__/install-state.gz'
patchFolder: './.yarn/patches'
pnpUnpluggedFolder: './node_modules/.__yarn__/unplugged'
virtualFolder: './node_modules/.__yarn__/__virtual__'
